### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Calinou** [CptPotato/GodotThings#2]
A license should be added to this repository, so that users know their rights. See [Choose a License](https://choosealicense.com/) for more information :slightly_smiling_face:

**Comment by CptPotato** [comment]
Good idea.

When creating this I wasn't sure if this repo would be helpful to anyone and didn't really care what people do with the code :sweat_smile:. I'll rethink that and add a licence soon (it'll probably be MIT or CC0).

Edit: didn't mean to close
