### ISSUE TITLE
Smooth pixel filtering for GLES2

### ISSUE THREAD

**Issue by ghost** [CptPotato/GodotThings#4]
Add a shader for GLES2. This would be most useful for projects targeting web and mobile platforms.

**Comment by CptPotato** [comment]
Sadly the pixel shader derivatives (`dFdx/dFdy`) which are used for this filtering method are not supported in GLES2 as far as I know.

There is an approach without these derivatives (see `SmoothPixelManual.shader`) which should work as long as linear filtering is supported. It requires to manually calculate the scaling factor though.
